version: '3'

services:
  next-app:
    container_name: next-app
    env_file:
      - ../.env.production
    build:
      context: ../
      dockerfile: docker/prod.Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - my_network
  mongodb:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ../data:/data/db
    networks:
      - my_network

 # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
