version: '3'

services:
  next-app:
    container_name: next-app
    env_file:
      - ../.env.development
    build:
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ../src:/app/src
      - ../public:/app/public
    depends_on:
      - mongodb
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
  mongodb:
    restart: always
    image: mongo:4.2.0
    volumes:
      - ../data:/data/db
    networks:
      - my_network
    expose:
      - 27017:27017
  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
